// <auto-generated />
using System;
using AIDbOptimize.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIDbOptimize.Infrastructure.Persistence.Migrations.ControlPlane
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260429031727_AlignWorkflowTargetState")]
    partial class AlignWorkflowTargetState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.AgentMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("SequenceNo")
                        .HasColumnType("bigint");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkflowSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowSessionId");

                    b.HasIndex("AgentSessionId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("idx_agent_messages_session_sequence");

                    b.ToTable("agent_messages", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveSummaryId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastCompactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageGroupCount")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerializedSessionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionStateJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActiveSummaryId");

                    b.HasIndex("WorkflowSessionId")
                        .HasDatabaseName("idx_agent_sessions_workflow_session_id");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSummaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SourceEndSequence")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceStartSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId")
                        .HasDatabaseName("idx_agent_summaries_agent_session_id");

                    b.ToTable("agent_summaries", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.DataInitializationRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("SeedVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("TargetOrderCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Engine", "DatabaseName", "SeedVersion")
                        .IsUnique();

                    b.ToTable("data_initialization_runs", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.McpConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatabaseConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EnvironmentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastDiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ServerArgumentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServerCommand")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Engine")
                        .HasDatabaseName("idx_mcp_connections_engine");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("idx_mcp_connections_is_default");

                    b.ToTable("mcp_connections", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.McpToolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InputSchemaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWriteTool")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "ToolName")
                        .IsUnique();

                    b.ToTable("mcp_tools", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.McpToolExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExecutionScope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RequestPayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResponsePayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkflowNodeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("WorkflowSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ToolId");

                    b.HasIndex("WorkflowSessionId");

                    b.HasIndex("WorkflowSessionId", "WorkflowNodeName")
                        .HasDatabaseName("idx_mcp_tool_executions_session_node");

                    b.ToTable("mcp_tool_executions", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowCheckpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentStateRefsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckpointRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentNodeKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayloadCompressed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadEncoding")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("PayloadSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("PendingRequestsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WorkflowSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowSessionId", "CheckpointRef")
                        .HasDatabaseName("idx_workflow_checkpoints_session_ref");

                    b.HasIndex("WorkflowSessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("idx_workflow_checkpoints_session_sequence");

                    b.ToTable("workflow_checkpoints", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("McpToolExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("NodeExecutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReviewTaskId")
                        .HasColumnType("uuid");

                    b.Property<long>("SequenceNo")
                        .HasColumnType("bigint");

                    b.Property<string>("SpanId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkflowSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("McpToolExecutionId");

                    b.HasIndex("NodeExecutionId");

                    b.HasIndex("ReviewTaskId");

                    b.HasIndex("WorkflowSessionId", "OccurredAt")
                        .HasDatabaseName("idx_workflow_events_session_occurred_at");

                    b.HasIndex("WorkflowSessionId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("idx_workflow_events_session_sequence");

                    b.ToTable("workflow_events", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowNodeExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputPayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OutputPayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TokenUsageJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId");

                    b.HasIndex("WorkflowSessionId", "NodeKey", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("idx_workflow_node_executions_session_node_attempt");

                    b.ToTable("workflow_node_executions", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowReviewTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CheckpointId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("text");

                    b.Property<string>("EngineCheckpointRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EngineRunId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("NodeExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("NodeExecutionId");

                    b.HasIndex("WorkflowSessionId", "Status")
                        .HasDatabaseName("idx_workflow_review_tasks_session_status");

                    b.ToTable("workflow_review_tasks", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveReviewTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentNodeKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EngineCheckpointRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EngineRunId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EngineStateJson")
                        .HasColumnType("text");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("InputPayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResultPayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveReviewTaskId");

                    b.HasIndex("AgentSessionId");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ConnectionId", "Status")
                        .HasDatabaseName("idx_workflow_sessions_connection_status");

                    b.ToTable("workflow_sessions", (string)null);
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.AgentMessageEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSessionEntity", "AgentSession")
                        .WithMany("Messages")
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", "WorkflowSession")
                        .WithMany("AgentMessages")
                        .HasForeignKey("WorkflowSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentSession");

                    b.Navigation("WorkflowSession");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSessionEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSummaryEntity", "ActiveSummary")
                        .WithMany()
                        .HasForeignKey("ActiveSummaryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", "WorkflowSession")
                        .WithMany("AgentSessions")
                        .HasForeignKey("WorkflowSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveSummary");

                    b.Navigation("WorkflowSession");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSummaryEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSessionEntity", "AgentSession")
                        .WithMany("Summaries")
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentSession");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.McpToolEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.McpConnectionEntity", "Connection")
                        .WithMany("Tools")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.McpToolExecutionEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.McpConnectionEntity", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.McpToolEntity", "Tool")
                        .WithMany("Executions")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", "WorkflowSession")
                        .WithMany("ToolExecutions")
                        .HasForeignKey("WorkflowSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Connection");

                    b.Navigation("Tool");

                    b.Navigation("WorkflowSession");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowCheckpointEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", "WorkflowSession")
                        .WithMany("Checkpoints")
                        .HasForeignKey("WorkflowSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowSession");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowEventEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.McpToolExecutionEntity", "McpToolExecution")
                        .WithMany("WorkflowEvents")
                        .HasForeignKey("McpToolExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowNodeExecutionEntity", "NodeExecution")
                        .WithMany("Events")
                        .HasForeignKey("NodeExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowReviewTaskEntity", "ReviewTask")
                        .WithMany("Events")
                        .HasForeignKey("ReviewTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", "WorkflowSession")
                        .WithMany("Events")
                        .HasForeignKey("WorkflowSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpToolExecution");

                    b.Navigation("NodeExecution");

                    b.Navigation("ReviewTask");

                    b.Navigation("WorkflowSession");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowNodeExecutionEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSessionEntity", "AgentSession")
                        .WithMany("NodeExecutions")
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", "WorkflowSession")
                        .WithMany("NodeExecutions")
                        .HasForeignKey("WorkflowSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentSession");

                    b.Navigation("WorkflowSession");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowReviewTaskEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowCheckpointEntity", "Checkpoint")
                        .WithMany()
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowNodeExecutionEntity", "NodeExecution")
                        .WithMany("ReviewTasks")
                        .HasForeignKey("NodeExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", "WorkflowSession")
                        .WithMany("ReviewTasks")
                        .HasForeignKey("WorkflowSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkpoint");

                    b.Navigation("NodeExecution");

                    b.Navigation("WorkflowSession");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", b =>
                {
                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowReviewTaskEntity", "ActiveReviewTask")
                        .WithMany()
                        .HasForeignKey("ActiveReviewTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSessionEntity", "PrimaryAgentSession")
                        .WithMany()
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIDbOptimize.Infrastructure.Persistence.Entities.McpConnectionEntity", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActiveReviewTask");

                    b.Navigation("Connection");

                    b.Navigation("PrimaryAgentSession");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.AgentSessionEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("NodeExecutions");

                    b.Navigation("Summaries");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.McpConnectionEntity", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.McpToolEntity", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.McpToolExecutionEntity", b =>
                {
                    b.Navigation("WorkflowEvents");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowNodeExecutionEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("ReviewTasks");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowReviewTaskEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("AIDbOptimize.Infrastructure.Persistence.Entities.WorkflowSessionEntity", b =>
                {
                    b.Navigation("AgentMessages");

                    b.Navigation("AgentSessions");

                    b.Navigation("Checkpoints");

                    b.Navigation("Events");

                    b.Navigation("NodeExecutions");

                    b.Navigation("ReviewTasks");

                    b.Navigation("ToolExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
